--USE [DB_TPM2018]
use kasetfms
GO

/****** Object:  Table [dbo].[TB_PREPARING_MOVE_TO_PLANTING]    Script Date: 9/18/2018 6:24:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_SCHEDULED_WEED_ELIMINATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PID] [int] NULL,
	[DETAIL] [nvarchar](1000) NULL,
	[ACTIVITY_DATE] [datetime] NULL,
	[WORK_AREA] [decimal](9, 4) NULL,
	[AMOUNT_RATE] [decimal](9, 2) NULL,
	[ADVANCE_AMOUNT] [decimal](9, 2) NULL,
	[TOTAL_AMOUNT] [decimal](9, 2) NULL,
	[STATUS_ID] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_TB_SCHEDULED_WEED_ELIMINATION_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


